# Site settings
author: Michael Nnaji
title: Journey to Fullstack
header-img: img/home-bg.png
email: mnnaji3@uwo.ca
copyright_name: Michael Nnaji
description: > # this means to ignore newlines until "baseurl:"
  Journey
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  mikennaji

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
